# vim: ft=tmux
set -g @catppuccin_flavor 'mocha'

# Some basic mocha colors.
set -g @ctp_bg "#24273a"
set -g @ctp_surface_1 "#494d64"
set -g @ctp_fg "#cad3f5"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_crust "#181926"

set -g mode-style "fg=#eee8d5,bg=#181926"

set -g message-style "fg=#eee8d5,bg=#181926"
set -g message-command-style "fg=#eee8d5,bg=#181926"

set -g pane-border-style "fg=#181926"
set -g pane-active-border-style "fg=#eee8d5"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#586e75,bg=#181926"

set -g status-bg "#181926"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#073642,bg=#eee8d5,bold] #S #[fg=#eee8d5,bg=#93a1a1,nobold,nounderscore,noitalics]#[fg=#15161E,bg=#93a1a1,bold] #(whoami) #[fg=#93a1a1,bg=#181926]"
set -g status-right "#[fg=#586e75,bg=#181926,nobold,nounderscore,noitalics]#[fg=#93a1a1,bg=#586e75]#[fg=#657b83,bg=#586e75,nobold,nounderscore,noitalics]#[fg=#93a1a1,bg=#657b83]#[fg=#93a1a1,bg=#657b83,nobold,nounderscore,noitalics]#[fg=#15161E,bg=#93a1a1,bold] #h "

setw -g window-status-activity-style "underscore,fg=#839496,bg=#002b36"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#89b4fa,bg=#181926"
setw -g window-status-format '#[fg=#181926,bg=#181926]#[default] #I  #{b:pane_current_path} #[fg=#181926,bg=#181926,nobold,nounderscore,noitalics]'
setw -g window-status-current-format '#[fg=#181926,bg=#89b4fa]#[fg=#89b4fa,bg=#000] #I #[fg=#000,bg=#89b4fa] #{b:pane_current_path} #[fg=#89b4fa,bg=#181926,nobold]'

# Make the status line more pleasant.
set -g status-left ""

# Ensure that everything on the right side of the status line
set -g status-right-length 100
